import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = () => (
  <nav className="bg-blue-600 text-white py-4">
    <div className="container mx-auto flex justify-between items-center px-4">
      <a href="/" className="text-lg font-semibold">
        QuizIt!
      </a>
      <ul className="flex space-x-4">
        <li>
          <a href="/" className="hover:underline">
            Home
          </a>
        </li>
        <li>
            <a href="/upload" className="hover:underline">
            Upload
            </a>
        </li>
        <li>
          <a href="/practice" className="hover:underline">
            Practice
          </a>
        </li>
      </ul>
    </div>
  </nav>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}